### PR TITLE
Switch appcuesId to apiKey

### PR DESCRIPTION
**Pull request by sperand-io**
corresponds with https://github.com/segmentio/mongo-scripts/pull/116

### CODE REVIEW

**Comment by sperand-io** [comment]
🚢

**Comment by hijonathan** [comment]
😢 just verified with a customer and locally that this is preventing new folks from using Appcues via Segment. If any of our customers trigger a rebundle of their Segment SDK, odds are this will also break their accounts as well.

**Comment by gamache** [comment]
This bug is still live.

**Comment by f2prateek** [comment]
Can you clarify what the error is?

**Comment by gamache** [comment]
`apiKey` is not a valid substitute for `appcuesId`, that's the error.  Appcues has discussed this with @sperand-io and we are assured that a fix is coming, but as of today we still have customers that can't use our Segment integrations correctly due to this bug.

**Pull request merged**
